### ISSUE TITLE
Arrow Key Incriment Increases Erroneously

### ISSUE THREAD

**Issue by Arries955** [h110m/NSFWDownloader#1]
If you open a comic and use the arrow keys to change pages it will increment by 1.
If you close the comic and open any comic and use the arrow keys to change pages
it will increment by 2.  This is every increasing for each additional comic opened.

This also seems to affect the auto page turn function where similarly it will increase 
the increment after each use.

**Comment by h110m** [comment]
Hey @Arries955,

Thanks for submitting your issue.
I will look into it and provide a fix in the next release.

**Comment by h110m** [comment]
@Arries955 i fixed this issue in the newest version of the NSFWDownloader --> https://github.com/h110m/NSFWDownloader/releases/tag/0.0.2

Have fun ^-^
