### ISSUE TITLE
Multporn URLs with 'gay_porn_comics' 

### ISSUE THREAD

**Issue by Arries955** [h110m/NSFWDownloader#2]
Some comics will switch there URL to include '.../gay_porn_comics/...' instead of '.../comics...' when you select them.  Inputting this into the program's downloader will result in nothing happening.

Example URL Input
https://multporn.net/gay_porn_comics/marco_diaz

**Comment by h110m** [comment]
Hey @Arries955,

thanks for your issue.
Currently, the downloader only supports "/comics" and "/pictures" URLs. I will look forward to including this with a couple more new comic links in the next release ^-^

Stay tuned 🥳

**Comment by h110m** [comment]
@Arries955 This issue was fixed in the latest release --> https://github.com/h110m/NSFWDownloader/releases
With a lot of other things 

Have fun ^-^
